AWSTemplateFormatVersion: '2010-09-09'
Description: 'Desplegando SG_MeliSec'

############################## Parameters ####################################################

Parameters:

  VpcId:
    Description: The VPC of the worker instances
    Type: AWS::EC2::VPC::Id
    Default: vpc-0b5344304b52a4cd8

######################################## Resources ######################################
Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: securityGroup-MeliSec
      GroupDescription: Allow conection to client
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 181.131.193.74/32

###############################################################

