AWSTemplateFormatVersion: '2010-09-09'
Description: 'Desplegando EC2'

############################## Parameters ####################################################

Parameters:

  environment:
    Description: Ambiente donde se despliega.
    Type: String
    Default: dev

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro

  ImageId:
    Description: EC2 Instance AMI
    Type: AWS::EC2::Image::Id
    Default: ami-02c27944e9187fdb0

  VpcId:
    Description: The VPC of the worker instances
    Type: AWS::EC2::VPC::Id
    Default: vpc-0b5344304b52a4cd8

  Subnet:
    Description: The subnets where workers can be created.
    Type: AWS::EC2::Subnet::Id
    Default: subnet-03f8eb5e3b7805d37 

  DisableApiTermination:
     Description: desible or enable termination
     Type: String
     Default: false
  

######################################## Resources ######################################
Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: securityGroup-Carlos
      GroupDescription: Allow conection to client
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 10.104.60.0/22


  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - InstanceSecurityGroup
      - ManagedInstanceRole
    Properties:
      SubnetId: !Ref Subnet
      DisableApiTermination: !Ref DisableApiTermination
      ImageId: 
        Ref: ImageId
      Tags:
        -
          Key: Name
          Value: EC2-MeliSec
      SecurityGroupIds:
      - Ref: InstanceSecurityGroup
      InstanceType: 
        Ref: InstanceType
      IamInstanceProfile: !Ref ManagedInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash


  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Path: "/"

  ManagedInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref ManagedInstanceRole
      InstanceProfileName: ProfileCarlos

  
###############################################################

