AWSTemplateFormatVersion: '2010-09-09'
Description: 'Desplegando EC2_MeliSec'

############################## Parameters ####################################################

Parameters:

  environment:
    Description: Ambiente donde se despliega.
    Type: String
    Default: dev

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro

  ImageId:
    Description: EC2 Instance AMI
    Type: AWS::EC2::Image::Id
    Default: ami-02c27944e9187fdb0

  VpcId:
    Description: The VPC of the worker instances
    Type: AWS::EC2::VPC::Id
    Default: vpc-0b5344304b52a4cd8

  Subnet:
    Description: The subnets where workers can be created.
    Type: AWS::EC2::Subnet::Id
    Default: subnet-03f8eb5e3b7805d37 

  DisableApiTermination:
     Description: desible or enable termination
     Type: String
     Default: false
  

######################################## Resources ######################################
Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: securityGroup-MeliSec
      GroupDescription: Allow conection to client
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 181.131.193.74/32


  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - InstanceSecurityGroup
      - ManagedInstanceRole
    Properties:
      SubnetId: !Ref Subnet
      DisableApiTermination: !Ref DisableApiTermination
      ImageId: 
        Ref: ImageId
      Tags:
        -
          Key: Name
          Value: EC2-MeliSec
      SecurityGroupIds:
      - Ref: InstanceSecurityGroup
      InstanceType: 
        Ref: InstanceType
      IamInstanceProfile: !Ref ManagedInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          mkdir /tmp/ssm
          cd /tmp/ssm
          wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
          sudo dpkg -i amazon-ssm-agent.deb
          sudo -i
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common
          y
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
          sudo apt update
          apt-cache policy docker-ce
          sudo apt install docker-ce
          y
          sudo systemctl status docker
          sudo apt install python3-pip
          y
          pip install Flask
          sudo pip install pymongo
          bash

  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Path: "/"

  ManagedInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref ManagedInstanceRole
      InstanceProfileName: ProfileMeliSec

  
###############################################################

